import type { RoundRequest } from "../types/round-request"

export const mockRoundRequests: RoundRequest[] = [
  {
    id: "1",
    nickname: "ゴルフ太郎",
    playDateSpecified: "2024-01-15",
    playDateFlexible: "",
    preferredArea: ["南関東（埼玉、千葉、東京、神奈川）"],
    courseType: "山岳",
    hasCompanion: false,
    companionNickname: "",
    playStyle: ["2サムOK", "3サムOK"],
    shuttleService: false,
    requirements: "平日にゴルフを楽しめる仲間を探しています。初心者の方も大歓迎です！",
    createdAt: "2024-01-10",
    contact: "tanaka@example.com",
  },
  {
    id: "2",
    nickname: "ゴルフ次郎",
    playDateSpecified: "",
    playDateFlexible: "週末希望",
    preferredArea: ["東海（静岡、岐阜、愛知、三重）"],
    courseType: "シーサイド",
    hasCompanion: true,
    companionNickname: "ゴルフ花子",
    playStyle: ["4サム希望", "キャディ付"],
    shuttleService: true,
    requirements: "早朝スタートで1日を有効活用しましょう！競技志向の方歓迎です。",
    createdAt: "2024-01-08",
    contact: "sato@example.com",
  },
  {
    id: "3",
    nickname: "ゴルフ美",
    playDateSpecified: "2024-01-25",
    playDateFlexible: "",
    preferredArea: ["南関東（埼玉、千葉、東京、神奈川）"],
    courseType: "指定しない",
    hasCompanion: false,
    companionNickname: "",
    playStyle: ["スループレー", "2サムOK"],
    shuttleService: false,
    requirements: "ゴルフを始めたばかりの女性同士で楽しくラウンドしませんか？",
    createdAt: "2024-01-12",
    contact: "yamada@example.com",
  },
  {
    id: "4",
    nickname: "ゴルフ四郎",
    playDateSpecified: "2024-01-20",
    playDateFlexible: "",
    preferredArea: ["北関東（茨城、栃木、群馬、埼玉、山梨、長野）"],
    courseType: "丘陵",
    hasCompanion: true,
    companionNickname: "ゴルフ五郎",
    playStyle: ["3サムOK", "4サム希望"],
    shuttleService: true,
    requirements: "北関東エリアでのんびりゴルフを楽しみましょう。送迎もできます！",
    createdAt: "2024-01-09",
    contact: "golf4@example.com",
  },
]
